server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    resolver 127.0.0.11 ipv6=off;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        set $api_upstream http://api:8080;
        proxy_pass $api_upstream/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
